name: Get GitHub Workflow approver

# Gets the name of the person who has approved a workflow job
# This is typically used to get the person who approved
# deployment to an environment
#
# Uses the GitHub Actions approvals API which only requires
# the default GITHUB_TOKEN with actions:read permission

inputs:
  environment-name:
    description: "Environment name to get approval for (e.g., 'Stage', 'Production')"
    required: true
  gh-token:
    description: "GitHub token (defaults to GITHUB_TOKEN)"
    required: false
    default: ${{ github.token }}

outputs:
  approver:
    description: "Name of approver"
    value: ${{ steps.get-approver.outputs.approver }}
  approval-json-file:
    description: "GitHub approval json file"
    value: ${{ steps.get-approver.outputs.approval-json-file }}

runs:
  using: "composite"
  steps:
    - name: Get approval actor from approvals API
      id: get-approver
      shell: bash
      run: |
        API_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/approvals"
        
        echo "Fetching approvals for run ${{ github.run_id }}..."
        curl -s -H "Authorization: Bearer ${{ inputs.gh-token }}" \
          -H "Accept: application/vnd.github+json" \
          "$API_URL" > approvals.json
        
        echo "Approvals response:"
        cat approvals.json | jq .
        
        # Extract the user who approved the specified environment
        APPROVAL_ENTRY=$(jq -r --arg env "${{ inputs.environment-name }}" \
          '.[] | select(.environments[].name == $env)' \
          approvals.json | head -1)
        
        if [[ -z "$APPROVAL_ENTRY" ]]; then
          echo "No approval found for environment: ${{ inputs.environment-name }}"
          exit 1
        fi
        
        echo "Found matching approval:"
        echo "$APPROVAL_ENTRY" | jq .
        echo "$APPROVAL_ENTRY" > approver.json
        
        APPROVER=$(echo "$APPROVAL_ENTRY" | jq -r '.user.login')
        
        if [[ -z "$APPROVER" || "$APPROVER" == "null" ]]; then
          echo "Could not extract approver from approval data"
          exit 1
        fi
        
        echo "Approver: $APPROVER"
        echo "approver=$APPROVER" >> $GITHUB_OUTPUT
        echo "approval-json-file=approver.json" >> $GITHUB_OUTPUT
